
project_id = "ladvarsisubtxnkbpgbh"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[functions.bunny-upload]
verify_jwt = false
