
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ladvarsisubtxnkbpgbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZHZhcnNpc3VidHhua2JwZ2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mjk5MzgsImV4cCI6MjA2MjAwNTkzOH0.FglvWPNx-EU-UjMhfOcM_Sxh54ibydzdbcwN7muZNKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add this temporary solution until the Database type gets refreshed
declare module '@supabase/supabase-js' {
  interface PostgrestQueryBuilder<Schema> {
    from: (relation: string) => any;
  }
}
